server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        type: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-registration
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      generate_statistics: true
      cache:
         use_second_level_cache: true
         region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory